sudo: required

language: perl6

perl6:
  - latest

before_install:
  - perl6 -v
install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update               ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libimlib2-dev ; fi
  - rakudobrew build-panda
  - panda installdeps .
script: "DISPLAY= prove -e 'perl6 -Ilib' t"
